### Get Employee Local details
GET http://localhost:4004/odata/v2/employee-transactional/EmployeeLocal

### Get Employee Data
GET http://localhost:4004/odata/v2/employee-transactional/Employeedb;

### Get Employee Data
GET http://localhost:4004/odata/v2/employee-transactional/Employees